on:
  push:
    branches:
      - main
name: 🚀 Deploy *myapis app* on push
jobs:
  web-deploy:
    name: 🎉 Deploy Production Environment
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files Production Environment -*myapis app*
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_pass }}
          server-dir: insighthall/myapis/
